version: '3.1'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx/
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress-v:/var/www/html/wordpress
    networks:
      - inception-network
    restart: always

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/
    volumes:
      - mariadb-v:/var/lib/mysql
    restart: always
    networks:
      - inception-network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress/
    restart: always
    networks:
      - inception-network
    volumes:
      - wordpress-v:/var/www/html/wordpress
    env_file:
      - .env

volumes:
  mariadb-v:
    driver_opts:
      type: 'none'
      device: home/${USER}/data/mariadb
      o: 'bind'
  wordpress-v:
    driver_opts:
      type: 'none'
      device: home/${USER}/data/wordpress
      o: 'bind'

networks:
  inception-network:
    driver: bridge
